<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ABCpdf" Version="12.5.1" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickBase-C-Sharp-SDK\Intuit.QuickBase.Client\Intuit.QuickBase.Client.csproj" />
    <ProjectReference Include="..\QuickBase-C-Sharp-SDK\Intuit.QuickBase.Core\Intuit.QuickBase.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PdfTemplates\" />
    <Folder Include="NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <NativeLibs Remove="Controllers\Pdf\TicketInvoiceController.cs" />
  </ItemGroup>

  <ItemGroup>
    <NativeLibs Remove="Modules\TicketBuilder.cs" />
  </ItemGroup>

</Project>
